### ISSUE TITLE
Gray screen with nothing on Mac OS 10.10.1 when launching application

### ISSUE THREAD

**Issue by johnwschan** [rawberg/ubuntu-server-gui#23]
As per title. 
I will try to compile a copy from source when I have time.
In the meantime, here's a screen capture of the issue.
![screen shot 2015-01-12 at 12 44 01 am](https://cloud.githubusercontent.com/assets/869270/5695937/1e9e8184-99f4-11e4-91df-09be3abf860f.png)

**Comment by rawberg** [comment]
yeah its totally broken because it's not pulling the latest files from the web server. thanks for letting me know. looking into this now.

**Comment by rawberg** [comment]
this specific loading issue should be fixed now. let me know if you still have problems!

**Comment by johnwschan** [comment]
It's still showing the blank screen like before.

**Comment by rawberg** [comment]
I tried opening again and it was able to load. Could you try clearing your DNS cache?

**Comment by LazerTiberius** [comment]
Got the same problem on win 8.1 x64, any ideas?

**Comment by Craytor** [comment]
Same issue here on Windows 8.1 64-bit.
