### ISSUE TITLE
Installation Fails on 'git submodule update'

### ISSUE THREAD

**Issue by edglazer** [rawberg/ubuntu-server-gui#24]
Mac 10.10.1 got the submodule initialized, but received this error on update step of install:

remote: Repository not found.
fatal: repository 'https://github.com/rawberg/bootstrap.git/' not found
Clone of 'https://github.com/rawberg/bootstrap.git' into submodule path 'web/css/bootstrap' failed

Did I miss something, perhaps?
Thanks!

**Comment by rawberg** [comment]
accidentally deleted my bootstrap fork. fixed now! thanks for letting me know!

**Comment by edglazer** [comment]
Not at all, thank you!
