### ISSUE TITLE
Grayscreen (Seems to be a Javascipt Problem)

### ISSUE THREAD

**Issue by tk-s** [rawberg/ubuntu-server-gui#27]
By launching http://app.ubuntuservergui.com/ directly (from wich the Application tries to load Boot.js) the same problem occurs and the JS-Console states:

Uncaught TypeError: Cannot read property 'top' of undefined at /app/Boot.js:16158

**Comment by rawberg** [comment]
going to look into this issue today, apologies for the lag.

**Comment by rawberg** [comment]
this should be fixed now. apologies for the delay, a whole new version of the app is under development :)
